# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4b09b6e16a227f07579db5d2755ac062"
name = "thank-you-order-status"
handle = "thank-you-order-status-21"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "apps2023.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
